[package]
name = "rustyalgebra"
version = "0.1.0"
authors = ["Sam Morley <sam@inakleinbottle.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
